var dados = {
  "login": "AbnerRibeiro",
  "id": 51347072,
  "node_id": "MDQ6VXNlcjUxMzQ3MDcy",
  "avatar_url": "https://avatars2.githubusercontent.com/u/51347072?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/AbnerRibeiro",
  "html_url": "https://github.com/AbnerRibeiro",
  "followers_url": "https://api.github.com/users/AbnerRibeiro/followers",
  "following_url": "https://api.github.com/users/AbnerRibeiro/following{/other_user}",
  "gists_url": "https://api.github.com/users/AbnerRibeiro/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/AbnerRibeiro/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/AbnerRibeiro/subscriptions",
  "organizations_url": "https://api.github.com/users/AbnerRibeiro/orgs",
  "repos_url": "https://api.github.com/users/AbnerRibeiro/repos",
  "events_url": "https://api.github.com/users/AbnerRibeiro/events{/privacy}",
  "received_events_url": "https://api.github.com/users/AbnerRibeiro/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Abner G. Ribeiro",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 7,
  "public_gists": 0,
  "followers": 3,
  "following": 2,
  "created_at": "2019-06-04T00:19:28Z",
  "updated_at": "2019-06-15T22:40:32Z"
}